# Generated by Django 4.2.3 on 2023-07-23 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='text',
            field=models.CharField(default='', max_length=1000000000),
        ),
    ]
