# Generated by Django 4.2.3 on 2023-07-23 16:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_alter_file_text'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='file',
            new_name='fileUpload',
        ),
        migrations.RenameField(
            model_name='fileupload',
            old_name='nomPlan',
            new_name='name',
        ),
    ]
